[build]
  command = "gatsby build"
  publish = "public"
  environment = { NODE_VERSION = "18.20.7" }

[dev]
  command = "gatsby develop"
  port = 8000
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-gatsby"

# ✅ Redirects für NetlifyCMS (Admin-Login) und SPA
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Header für Sicherheit & Caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"

# ✅ Google Analytics (optional über ENV-Variable)
#[[plugins]]
# package = "netlify-plugin-google-analytics"
#  [plugins.inputs]
#   trackingId = "${GATSBY_GOOGLE_ANALYTICS_ID}"
